name: WarpSign
main: be.Balor.bukkit.AdminCmd.AdminCmd
version: ${project.version} (BUILD ${git.build.time})
authors: [Balor]
depend: [AdminCmd]
description: >
             This plugin is a addon to AdminCmd to add Warping Signs.
commands: