name: WarpSign
main: be.Balor.WarpSign.WarpSign
version: ${project.version} (BUILD ${git.build.time})
author: Balor
depend: [AdminCmd]
class-loader-of: AdminCmd
description: >
             This plugin is a addon to AdminCmd to add Warping Signs.
commands: